teacher_comments_analysis/login/urls.py
from django.conf.urls import url
from . import views

app_name = 'login'

urlpatterns = [
    # ex: /login/
    url(r'^$', views.login, name='login'),
    # ex: /login/5/
    url(r'^(?P<teacher_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /login/5/results/
    url(r'^(?P<teacher_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /login/5/add/
    url(r'^(?P<teacher_id>[0-9]+)/add/$', views.add, name='add'),

]

teacher_comments_analysis/teacher_comments_analysis/urls.py
from django.contrib import admin
from login import views
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', views.index),
    url(r'^tlogin/', views.tlogin),
    url(r'^login/', include('login.urls')),
    url(r'^about/', views.about),
    url(r'^teacher/', views.teacher),
    url(r'^logout/', views.logout),
    url(r'', views.index),


]

teacher_comments_analysis/login/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Comment(models.Model):
    comment = models.CharField(max_length=256)
    created_time = models.DateField(auto_now_add=True)
    teacher = models.ForeignKey('Teacher', models.DO_NOTHING)
    student = models.ForeignKey('Student', models.DO_NOTHING)

    def __str__(self):
        return self.comment

    class Meta:
        db_table = 'comment'


class Student(models.Model):
    student_name = models.CharField(max_length=16)
    student_password = models.CharField(max_length=16)
    created_time = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.student_name

    class Meta:
        db_table = 'student'


class Teacher(models.Model):
    teacher_name = models.CharField(max_length=16)
    teacher_password = models.CharField(max_length=16)
    crouse = models.CharField(max_length=16)
    created_time = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.teacher_name

    class Meta:
        db_table = 'teacher'

teacher_comments_analysis/login/views.py
from django.shortcuts import render
from django.shortcuts import redirect  # 用于重定向
from login import models
from .form import StudentForm
from .form import TeacherForm
from .models import Teacher
from .models import Comment
from django.shortcuts import get_object_or_404
import datetime
import jieba
import gensim
from gensim import corpora

from gensim import similarities
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
# Create your views here.
# 四个视图都返回一个render()调用，render方法接收request作为第一个参数
# 要渲染的页面为第二个参数
# 以及需要传递给页面的数据字典作为第三个参数（可以为空）
# 表示根据请求的部分，以渲染的HTML页面为主体，使用模板语言将数据字典填入，然后返回给用户的浏览器。


def index(request):
    pass
    return render(request, 'login/index.html')


def tlogin(request):
    # 判断用户是否已登录
    if request.session.get('is_login', None):
        return redirect("/index/")
    if request.method == 'POST':
        login_form = TeacherForm(request.POST)
        # print(username, password)
        if login_form.is_valid():
            username = login_form.cleaned_data['Tusername']
            password = login_form.cleaned_data['Tpassword']
            # 用户名合法性验证
            # 密码长度验证
            # ...
        try:
            teacher = models.Teacher.objects.get(teacher_name=username)
            print("用户名为：", username)
            if teacher.teacher_password == password:
                print("密码为：", password)
                request.session['is_login'] = True
                request.session['is_tea'] = True
                request.session['user_id'] = teacher.id
                request.session['user_name'] = teacher.teacher_name
                return redirect('/index/')
            else:
                print("密码错误！")
        except:
            print("用户名不存在！")
        return render(request, 'login/tlogin.html', locals())
    login_form = TeacherForm()
    return render(request, 'login/tlogin.html', locals())


def login(request):
    # 判断用户是否已登录
    if request.session.get('is_login', None):
        return redirect("/index/")
    if request.method == 'POST':
        login_form = StudentForm(request.POST)
        # print(username, password)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            # 用户名合法性验证
            # 密码长度验证
            # ...
        try:
            student = models.Student.objects.get(student_name=username)
            # print("用户名为：", username)
            if student.student_password == password:
                # print("密码为：", password)
                request.session['is_login'] = True
                request.session['is_tea'] = False
                request.session['user_id'] = student.id
                request.session['user_name'] = student.student_name
                return redirect('/index/')
            else:
                print("密码错误！")
        except:
            print("用户名不存在！")
        return render(request, 'login/login.html', locals())
    login_form = StudentForm()
    return render(request, 'login/login.html', locals())


def about(request):
    pass
    return render(request, 'login/about.html')


def teacher(request):
    try:
        teacher = models.Teacher.objects.all()
        #print("老师列表：")
        #print(teacher)
        student = models.Student.objects.all()
        #print("学生列表：")
        #print(student)
        comment = models.Comment.objects.all()
        #print("评论列表：")
        #print(comment)
        #print(student[0].student_name, student[1].student_name)
        print(comment[0].student, comment[0].comment)
    except:
        print("无数据！")
    teacher_list = models.Teacher.objects.all()
    return render(request, 'login/teacher.html', {'data': teacher_list})


# 生成评价标签词云
def ciyun(f):
    from wordcloud import WordCloud
    import matplotlib.pyplot as plt
    import pygal

    # f = open('data/语料库.txt', 'r', encoding="utf-8").read()
    #f = "幽默风趣 幽默 亲切 很好 很好 很好 思维清晰 思维清晰 思维清晰 思维清晰 课程简单 适合初学者 有耐心 课程不错 课程简单 适合初学者 有耐心 课程不错 课程简单 适合初学者 有耐心 课程不错"
    wordcloud = WordCloud(font_path="C:/windows/Fonts/simfang.ttf", background_color="white", width=600, height=300,
                          margin=2).generate(f)

    plt.imshow(wordcloud)
    plt.axis("off")
    plt.show()
    wordcloud.to_file('static/images/ciyun.jpg')  # 保存图片


# 将原始评价与前期生成的评价标签做相似度计算，对每一条原始评价生成评论标签
def newdata(l1, a):
    from gensim import models
    all_doc_list = []
    for doc in l1:
        doc_list = [word for word in jieba.cut(doc)]
        all_doc_list.append(doc_list)

    #print("分词结果：", all_doc_list)
    doc_test_list = [word for word in jieba.cut(a)]

    # 制作语料库
    dictionary = corpora.Dictionary(all_doc_list)  # 制作词袋
    # 词袋的理解
    # 词袋就是将很多很多的词,进行排列形成一个 词(key) 与一个 标志位(value) 的字典
    # 例如: {'什么': 0, '你': 1, '名字': 2, '是': 3, '的': 4, '了': 5, '今年': 6, '几岁': 7, '多': 8, '有': 9, '胸多大': 10, '高': 11}
    # 至于它是做什么用的,带着问题往下看

    #print("token2id", dictionary.token2id)
    #print("dictionary", dictionary, type(dictionary))

    corpus = [dictionary.doc2bow(doc) for doc in all_doc_list]
    # 语料库:
    # 这里是将all_doc_list 中的每一个列表中的词语 与 dictionary 中的Key进行匹配
    # 得到一个匹配后的结果,例如['你', '今年', '几岁', '了']
    # 就可以得到 [(1, 1), (5, 1), (6, 1), (7, 1)]
    # 1代表的的是 你 1代表出现一次, 5代表的是 了  1代表出现了一次, 以此类推 6 = 今年 , 7 = 几岁
    #print("corpus", corpus, type(corpus))

    # 将需要寻找相似度的分词列表 做成 语料库 doc_test_vec
    doc_test_vec = dictionary.doc2bow(doc_test_list)
    #print("doc_test_vec", doc_test_vec, type(doc_test_vec))

    # 将corpus语料库(初识语料库) 使用Lsi模型进行训练
    lsi = models.LsiModel(corpus)
    # 这里的只是需要学习Lsi模型来了解的,这里不做阐述
    #print("lsi", lsi, type(lsi))
    # 语料库corpus的训练结果
    #print("lsi[corpus]", lsi[corpus])
    # 获得语料库doc_test_vec 在 语料库corpus的训练结果 中的 向量表示
    #print("lsi[doc_test_vec]", lsi[doc_test_vec])

    # 文本相似度
    # 稀疏矩阵相似度 将 主 语料库corpus的训练结果 作为初始值
    index = similarities.SparseMatrixSimilarity(lsi[corpus], num_features=len(dictionary.keys()))
    #print("index", index, type(index))

    # 将 语料库doc_test_vec 在 语料库corpus的训练结果 中的 向量表示 与 语料库corpus的 向量表示 做矩阵相似度计算
    sim = index[lsi[doc_test_vec]]
    #print("sim", sim, type(sim))

    # 对下标和相似度结果进行一个排序,拿出相似度最高的结果
    # cc = sorted(enumerate(sim), key=lambda item: item[1],reverse=True)
    cc = sorted(enumerate(sim), key=lambda item: -item[1])
    #print(cc)
    text = l1[cc[0][0]]
    #print(a, text)
    return text

def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/index/")
    request.session.flush()
    return redirect("/index/")


def detail(request, teacher_id):
    teacher_list = get_object_or_404(Teacher, pk=teacher_id)
    return render(request, 'login/detail.html', {'teacher': teacher_list})


def add(request, teacher_id):

    if request.method == 'POST':
        newcomment = request.POST.get('comment')
        models.Comment.objects.create(
        # 向数据库中插入数据
        comment=newcomment,
        teacher_id=teacher_id,
        student_id=request.session['user_id'],
        created_time=datetime.date.today()
    )
    #newcomment = request.POST['comment']
    #comment = Comment(comment=newcomment, teacher_id=teacher_id, student_id=request.session['user_id'],created_time=datetime.date.today())
    #comment.save()
    # 成功处理数据后，自动跳转到结果页面，防止用户连续多次提交。
    #HttpResponseRedirect(reverse('login:results', args=(teacher.id,)))

    # 读取
    items = open("data/myphrase.txt", "r", encoding="utf-8").read()
    list = items.split()
    #print(list)
    teacher = get_object_or_404(Teacher, pk=teacher_id)
    #print("教师评价查询：", teacher.comment_set.all())

    # 生成评价标签
    label_list = []
    for comment in teacher.comment_set.all():
        label = newdata(list, comment.comment)
        #print("生成的标签为：", label)
        label_list.append(label)
    f = " ".join(label_list)
    # 生成词云
    ciyun(f)

    return render(request, 'login/results.html', {'teacher': teacher})


def results(request, teacher_id):
    # 读取
    items = open("data/myphrase.txt", "r", encoding="utf-8").read()
    list = items.split()
    # print(list)
    teacher = get_object_or_404(Teacher, pk=teacher_id)
    # print("教师评价查询：", teacher.comment_set.all())

    # 生成评价标签
    label_list = []
    for comment in teacher.comment_set.all():
        label = newdata(list, comment.comment)
        print("生成的标签为：", label)
        label_list.append(label)
    f = " ".join(label_list)
    # 生成词云
    ciyun(f)
    return render(request, "login/results.html", {'teacher': teacher})

teacher_comments_analysis/login/templates/login/about.html
{% extends 'base1.html' %}
{% load staticfiles %}
{% block content %}
	<!-- banner -->
	<div class="banner-1">
	</div> 
	<!-- //banner -->
	<!-- about -->
	<div class="about">
		<div class="container">  
			<div class="w3ls-title">
				<h3 class="agileits-title">About Us</h3> 
			</div> 
			<div class="about-w3ls-row"> 
				<div class="col-md-5 about-left">
					<img src="{% static 'images/about.jpg' %}" class="img-responsive" alt=""/>
				</div>
				<div class="col-md-7 about-right"> 
					<div class="about-agile-row">
						<div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
							<ul id="myTab" class=" nav-tabs" role="tablist">
								<li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">About</a></li>
								<li role="presentation"><a href="#carl" role="tab" id="carl-tab" data-toggle="tab" aria-controls="carl"> Features</a></li>
							</ul> 
							<div class="clearfix"> </div>
							<div id="myTabContent" class="tab-content">
								<div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
									<div class="tabcontent-grids">
										<p>在这里，你可以对教师添加文字评价，系统
                                            会自动根据学生对教师的评价数据进行智能化分析，生成评价标签，
                                            并以词云的形式 展示出来，带给用户最直观的结果。</p>
										<ul>
											<li><i class="fa fa-check-square-o"></i> 新颖 </li>
											<li><i class="fa fa-check-square-o"></i> 词云展示 </li>
											<li><i class="fa fa-check-square-o"></i> 智能分析 </li>
											<li><i class="fa fa-check-square-o"></i> 十分高效 </li>
										</ul>
									</div>
								</div>
								<div role="tabpanel" class="tab-pane fade" id="carl" aria-labelledby="carl-tab">
									<div class="tabcontent-grids">
                                        <p>大部分高校不会将所有学生评价展示出来，而我们不仅对数据进行处理，而且在学生评价后可以看到所有的评价，实现了数据可视化。</p>
										<p>收集评价大部分高校采用的是书面的调查问卷，效果不好，而我们采用网站的方式，大大提高了效率。</p>
                                        <p>教师评价的数据繁多而复杂，处理很困难，我们的网站采用后台自动处理分析的方式，真正实现了智能化。</p>
                                        <p>由于评价数据较多，如果用户不想逐条查看，我们将评价抽取成标签，并制作成词云的方式，展示出来。</p>
                                        <p>我们将评价标签统计词频 ，后台将标签按频率由大到小展示出来，十分直观！</p>
									</div>
								</div>
								<div class="clearfix"> </div>
							</div>
						</div>
					</div>
				</div> 
				<div class="clearfix"> </div> 
			</div>
		</div>
	</div>
	<!-- //about -->
<!-- work start here -->
	<div class="work jarallax">
		<div class="container">
			<div class="work-agileinfo">
				<h3>Are You Impressed By Our Work?</h3>
				<p>Teacher Comments Analysis is there anyone who loves or pursues or desires to obtain pain.</p>
				<div class="w3btns-agile">
					<a href="contact.html">Get In Touch</a>
				</div>
			</div>
		</div>
	</div>
	<!-- work end here -->

		<!-- team -->
	<div class="team agileits-w3layouts">
		<div class="container"> 
		
			<div class="w3ls-title"> 
				<h3 class="agileits-title w3title1">Teacher Introduction</h3>
			</div>
			<div class="team-info wthree">
				<div class="col-md-6 team-w3lsgrids">
					<div class="team-left">
						<img class="img-responsive" src="{% static 'images/t1.jpg' %}" alt="">
					</div>
					<div class="team-right">
						<h4>Vivamus lias</h4>
						<p>Teacher lias is the most conscientious and reqponsible teacher. </p>
						<div class="social-icon">
							<a href="#" class="social-button twitter"><i class="fa fa-twitter"></i></a>
							<a href="#" class="social-button facebook"><i class="fa fa-facebook"></i></a> 
							<a href="#" class="social-button google"><i class="fa fa-google-plus"></i></a> 
							<a href="#" class="social-button dribbble"><i class="fa fa-dribbble"></i></a> 
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="col-md-6 team-w3lsgrids">
					<div class="team-left">
						<img class="img-responsive" src="{% static 'images/t2.jpg' %}" alt="">
					</div>
					<div class="team-right">
						<h4>Aliquam fauc </h4>
						<p>Teacher Aliquam is very beautiful and kind and students like him very much!</p>
						<div class="social-icon">
							<a href="#" class="social-button twitter"><i class="fa fa-twitter"></i></a>
							<a href="#" class="social-button facebook"><i class="fa fa-facebook"></i></a> 
							<a href="#" class="social-button google"><i class="fa fa-google-plus"></i></a> 
							<a href="#" class="social-button dribbble"><i class="fa fa-dribbble"></i></a> 
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="clearfix"> </div>
			</div>
			<div class="team-info team-row2">
				<div class="col-md-6 team-w3lsgrids">
					<div class="team-left">
						<img class="img-responsive" src="{% static 'images/t3.jpg' %}" alt="">
					</div>
					<div class="team-right">
						<h4>Donec nibh </h4>
						<p>Who is the most handsome man ? It must be Mr Donec !</p>
						<div class="social-icon">
							<a href="#" class="social-button twitter"><i class="fa fa-twitter"></i></a>
							<a href="#" class="social-button facebook"><i class="fa fa-facebook"></i></a> 
							<a href="#" class="social-button google"><i class="fa fa-google-plus"></i></a> 
							<a href="#" class="social-button dribbble"><i class="fa fa-dribbble"></i></a> 
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="col-md-6 team-w3lsgrids">
					<div class="team-left">
						<img class="img-responsive" src="{% static 'images/t1.jpg' %}" alt="">
					</div>
					<div class="team-right">
						<h4>Sed augue </h4>
						<p>Sed is a good man who can care about everyone.</p>
						<div class="social-icon">
							<a href="#" class="social-button twitter"><i class="fa fa-twitter"></i></a>
							<a href="#" class="social-button facebook"><i class="fa fa-facebook"></i></a> 
							<a href="#" class="social-button google"><i class="fa fa-google-plus"></i></a> 
							<a href="#" class="social-button dribbble"><i class="fa fa-dribbble"></i></a> 
						</div>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="clearfix"> </div>
			</div>
		</div>
	</div>
	<!-- //team -->
	{% endblock %}

teacher_comments_analysis/login/templates/login/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Contact</title> 
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="css/bootstrap.css" type="text/css" rel="stylesheet" media="all">
<link href="css/style.css" type="text/css" rel="stylesheet" media="all">
<link href="css/font-awesome.css" rel="stylesheet">  <!-- font-awesome icons --> 
<!-- //Custom Theme files -->
<!-- js -->
<script src="js/jquery-2.2.3.min.js"></script>   
<!-- //js -->
<!-- web-fonts -->
<link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i" rel="stylesheet">
<link href="http://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
<!-- //web-fonts --> 
</head>
<body>
	<!-- header -->
	<div class="header">
		<nav class="navbar navbar-default">
			<div class="container">
				<div class="navbar-header navbar-left wthree">
					<h1><a href="index.html">Edify<span>College Education</span></a></h1>
				</div>
				<!-- navigation -->
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<div class="header-right wthree">
					<div class="top-nav-text">
						<p>Call Us: <span>+00 111 2222 333</span></p>
						<div id="sb-search" class="sb-search">
							<form action="#" method="post">
								<input type="search" class="sb-search-input" name="Search" placeholder="Enter your search term..." id="search" required="">
								<input class="sb-search-submit" type="submit" value="">
								<span class="sb-icon-search"> </span>
							</form>
							<div class="clearfix"> </div>
							<!-- search-scripts -->
							<script src="js/classie.js"></script>
							<script src="js/uisearch.js"></script>
							<script>
								new UISearch( document.getElementById( 'sb-search' ) );
							</script>
							<!-- //search-scripts -->
						</div>
					</div>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">					
						<ul class="nav navbar-nav navbar-left cl-effect-14">
							<li><a href="index.html">Home</a></li>
							<li><a href="about.html">About</a></li>
							<li><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Pages <span class="caret"></span></a>
								<ul class="dropdown-menu">
									<li><a href="icons.html">Web Icons</a></li>
									<li><a href="codes.html">Short Codes</a></li>
								</ul>
							</li> 

							<li><a href="portfolio.html">Portfolio</a></li>
							<li><a href="contact.html" class="active">Contact Us</a></li>			
						</ul>		
						<div class="clearfix"> </div>
					</div><!-- //navigation -->
				</div>
				<div class="clearfix"> </div>
			</div>	
		</nav>		
	</div>	
	<!-- //header -->
	<!-- banner -->
	<div class="banner-1">
	</div> 
	<!-- //banner -->
		<!-- contact -->
	<div class="contact">
		<div class="team-info w3-agileits">
			<div class="container"> 
			<div class="w3ls-title"> 
				<h3 class="agileits-title w3title1">Contact Us</h3>
			</div>				
				<div class="contact-form">
					<form action="#" method="post">
						<input type="text" name="Name" placeholder="Name" required="">
						<input type="email" class="email" name="Email" placeholder="Email" required="">
						<input type="text" name="Phone" placeholder="Phone" required="">
						<textarea name="Message" placeholder="Message" required=""></textarea>
						<input type="submit" value="SUBMIT" >
					</form>
				</div>
			</div>
		</div>
	</div>		
	<!-- //contact -->
	<!-- map -->
	<div class="map w3layouts">
		<div class="col-md-8 map-left">
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d57537.641430789925!2d-74.03215321337959!3d40.719122105634035!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c24fa5d33f083b%3A0xc80b8f06e177fe62!2sNew+York%2C+NY%2C+USA!5e0!3m2!1sen!2sin!4v1456152197129" allowfullscreen=""></iframe>
		</div>
		<div class="col-md-4 map-wthree-right"> 
			<h4><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Address</h4>
			<p>CG 123 Sebas, Ba New York, USA</p>
			<h4><span class="glyphicon glyphicon-phone" aria-hidden="true"></span>Phone</h4>
			<p> +00 111 2222 333 </p>
			<h4><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>Email</h4>
			<p class="agile-last"><a href="mailto:info@example.com">mail@example.com</a></p> 
		</div>
		<div class="clearfix"> </div>
	</div>
	<!-- //map -->
	<!-- footer -->
	<div class="footer">
		<div class="container">
			<div class="col-md-4 w3layouts_footer_grid"> 
				<div class="title">
					<h2>Follow Us</h2> 
				</div>
				<div class="social-icon social_agileinfo">
					<a href="#" class="social-button twitter"><i class="fa fa-twitter"></i></a>
					<a href="#" class="social-button facebook"><i class="fa fa-facebook"></i></a> 
					<a href="#" class="social-button google"><i class="fa fa-google-plus"></i></a> 
					<a href="#" class="social-button dribbble"><i class="fa fa-dribbble"></i></a>
					<a href="#" class="social-button skype"><i class="fa fa-skype"></i></a>
				</div> 
			</div>
			<div class="col-md-8 w3layouts_footer_grid">
				<form action="#" method="post">
					<input type="email" name="Email" placeholder="Enter Your Email..." required="">
					<input type="submit" value="Submit"> 
					<div class="clearfix"> </div>
				</form>
				<ul class="w3l_footer_nav">
					<li><a href="index.html">Home</a></li> 
					<li><a href="about.html">About</a></li>
					<li><a href="icons.html">Icons</a></li> 
					<li><a href="portfolio.html">Portfolio</a></li>
					<li><a href="contact.html">Contact Us</a></li>	
				</ul> 
			</div>
			<div class="clearfix"> </div>
		</div>
	</div>
	<div class="footer-w3copy w3-agileits">
		<p>Copyright &copy; 2017.Company name All rights reserved.More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
	</div>
	<!-- //footer -->    
	
    <script src="js/bootstrap.js"></script>
</body>
</html>

teacher_comments_analysis/login/templates/login/detail.html
{% extends 'base1.html' %}

{% block content %}

    <div style="padding-left: 30px; padding-right: 30px; ">
    <div class="banner-1">
	</div>
        <br>
        <div class="w3ls-title">
				<h3 class="agileits-title w3title1">Teacher Comment</h3>
			</div>
        <p><strong>hi!</strong></p>
        <br>
        <div class="alert alert-warning" role="alert">
					<strong>请对{{ teacher.teacher_name }}进行评价...</strong>
				</div>
        <div class="span12" style="padding-bottom: 30px">
			<form action="{% url 'login:add' teacher.id %}" method="post">
                {% csrf_token %}
				<fieldset>
                    <label>评价内容</label><br>
                    <input type="text" style="height: 100px; width: 600px" name="comment"/>
                    <br>
                    <br>
                    <div style="padding-left: 230px">
                        <button type="reset" class="btn">清空</button>
                        <button type="submit" class="btn">提交</button>
                    </div>

				</fieldset>
			</form>
		</div>
    </div>

{% endblock %}

teacher_comments_analysis/login/templates/login/teacher.html
{% extends 'base1.html' %}

{% block content %}

<div style="padding-left: 30px; padding-right: 30px; ">
{% if request.session.is_login %}
    <p>你好,{{ request.session.user_name }}...</p>
    <br>
    <p>欢迎来到教师评价数据智能分析系统！！</p>
    <br>
    <div class="alert alert-success" role="alert">
					<strong>下面是教师列表...</strong>
    </div>
    <div class="bs-docs-example">
        <table class="table table-hover">
            <thead>
            <th>教师姓名</th>
            <th>课程名</th>
            <th>操作</th>
            </thead>
            <tbody>
            {% for line in data %}
            <tr>
            <td>{{ line.teacher_name }}</td>
            <td>{{ line.crouse }}</td>
                {% if request.session.is_tea == False %}
            <td><a href="{% url 'login:detail' line.id %}" >评教</a></td>
                    {% else %}
                    <td><a href="{% url 'login:results' line.id %}" >查看</a></td>
            {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}

    <div style="padding-left: 200px; padding-right: 200px; padding-bottom: 100px; padding-top: 100px;">
    <br>
        <h1>你尚未登录，只能访问公开内容！</h1>
    <br>
    </div>

    {% endif %}
</div>

{% endblock %}